provider: aws

primary:
  numNodes: 1

replicas:
  master: 1
  tserver: 1

resource:
  master:
    requests:
      cpu: 0.5
      memory: 0.5Gi
    limits:
      cpu: 1
      memory: 1Gi
  tserver:
    requests:
      cpu: 0.5
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2.5Gi

storage:
  master:
    size: 5Gi
    storageClass: ""
  tserver:
    size: 5Gi
    storageClass: ""

preflight:
  skipUlimit: true

enableLoadBalancer: false