apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: apisix
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apisix-ingress-controller
  ports:
  - name: http
    port: 80
    targetPort: 8080  # Controller HTTP port
    nodePort: 31334  