apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: apisix
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apisix
  ports:
  - name: http
    port: 80
    targetPort: 9080
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 9443