apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: order-route
  namespace: task2
spec:
  http:
  - name: order-route
    match:
      hosts:
      - localhost
      paths:
      - /order*
      - /orders
    backends:
    - serviceName: order-service
      servicePort: 8000
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["/order/(.*)", "/$1"]